#!/usr/bin/env python3
"""Render (and verify) the job-market statistics quoted in CURRICULUM.md and the chapters.

Hand-written counts ("93 mentions", "20+ postings") drift and cannot be re-checked. Every
number below is derived from the stored evidence in docs/research/jobs via the shared rules in
`scripts/job_evidence.py`, so any reader can reproduce or refute it.

Usage:
    python3 scripts/job_evidence_stats.py                 # markdown report
    python3 scripts/job_evidence_stats.py --json          # machine-readable
    python3 scripts/job_evidence_stats.py --out FILE      # archive the report as evidence
    python3 scripts/job_evidence_stats.py --check         # fail if quoted numbers drifted

--check verifies that the cluster table in CURRICULUM.md and every
"N of M postings with extracted body text (K mentions)" claim in chapters/ still match the
evidence; it does not rewrite prose. Run it in CI so hand-edited numbers cannot survive.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from job_evidence import JOBS_DIR_DEFAULT, stats  # noqa: E402

JOBS_DIR = JOBS_DIR_DEFAULT
ROOT = Path(__file__).resolve().parent.parent
CURRICULUM_ROW_RE = re.compile(r"^\|\s*([^|]+?)\s*\|\s*(\d+)/(\d+)\s*\|\s*(\d+)\s*\|")
CLAIM_RE = re.compile(r"(\d+) of (\d+) postings with extracted body text(?:\s*\((\d+) mentions\))?")


def render_markdown(rep: dict) -> str:
    lines = [
        "# Job-market evidence statistics",
        "",
        "Generated by `python3 scripts/job_evidence_stats.py`. Do not hand-edit:",
        "re-run the script and commit its output instead.",
        "",
        "## Corpus",
        "",
        f"- Postings discovered: **{rep['postings_discovered']}**",
        f"- With extracted body text (>= {rep['min_body_chars']} chars): **{rep['postings_with_body_text']}**",
        f"- Title-only (search result, no body): **{rep['postings_title_only']}**",
        f"- Skipped non-postings (login walls, search pages): **{rep['skipped_non_postings']}**",
        f"- `source-NN.md` files linked to a posting: **{rep['source_files']}**",
        "",
        "## Requirement clusters (over postings with extracted text)",
        "",
        "Ordered by observed frequency. A posting can cite several clusters, so the column does",
        "not sum to the corpus size; `mentions` counts keyword occurrences.",
        "",
        "| Cluster | Postings | Mentions |",
        "|---------|---------:|---------:|",
    ]
    for row in rep["clusters"]:
        lines.append(f"| {row['cluster']} | {row['postings']}/{rep['postings_with_body_text']} | {row['mentions']} |")
    lines += [
        "",
        "## Job families (tag counts)",
        "",
        "A posting may be tagged with several families; `Unclassified` cites none of the five",
        "target profiles.",
        "",
        "| Family | Postings |",
        "|--------|---------:|",
    ]
    for row in rep["families"]:
        lines.append(f"| {row['family']} | {row['postings']}/{rep['postings_with_body_text']} |")
    return "\n".join(lines) + "\n"


def check(root: Path, rep: dict) -> list[str]:
    """Compare the numbers quoted in the course against the evidence."""
    problems: list[str] = []
    expected = {row["cluster"]: row for row in rep["clusters"]}

    curriculum = root / "CURRICULUM.md"
    if curriculum.is_file():
        text = curriculum.read_text(encoding="utf-8", errors="replace")
        found: dict[str, tuple[int, int]] = {}
        found_order: list[str] = []
        for line in text.splitlines():
            m = CURRICULUM_ROW_RE.match(line)
            if not m:
                continue
            name = m.group(1).strip().strip("*")
            found[name] = (int(m.group(2)), int(m.group(4)))
            found_order.append(name)
        for name, row in expected.items():
            if name not in found:
                problems.append(f"CURRICULUM.md: cluster row missing or unparsable: {name}")
                continue
            postings, mentions = found[name]
            if postings != row["postings"] or mentions != row["mentions"]:
                problems.append(
                    f"CURRICULUM.md: {name} quotes {postings}/{row['postings']} postings, "
                    f"{mentions} mentions — evidence says {row['postings']} postings, {row['mentions']} mentions"
                )
        for name in found:
            if name not in expected:
                problems.append(f"CURRICULUM.md: cluster row not in the evidence: {name}")
        # CURRICULUM claims the table is ordered by observed frequency: enforce the order too.
        computed_order = [row["cluster"] for row in rep["clusters"]]
        if found_order and found_order != computed_order:
            common = min(len(found_order), len(computed_order))
            first = next((i for i in range(common) if found_order[i] != computed_order[i]), common)
            got = found_order[first] if first < len(found_order) else "(no row)"
            want = computed_order[first] if first < len(computed_order) else "(no cluster)"
            problems.append(
                "CURRICULUM.md: cluster table is not in observed-frequency order — "
                f"row {first + 1} is '{got}', evidence puts '{want}' there"
            )

    valid = {(row["postings"], rep["postings_with_body_text"], row["mentions"]) for row in rep["clusters"]}
    for chapter in sorted((root / "chapters").glob("*/README.md")):
        rel = chapter.relative_to(root)
        text = chapter.read_text(encoding="utf-8", errors="replace")
        for m in CLAIM_RE.finditer(text):
            postings, total, mentions = int(m.group(1)), int(m.group(2)), m.group(3)
            if total != rep["postings_with_body_text"]:
                problems.append(f"{rel}: claim says corpus of {total} postings; evidence says {rep['postings_with_body_text']}")
            if mentions is None:
                continue
            if (postings, total, int(mentions)) not in valid:
                problems.append(f"{rel}: claim '{m.group(0)}' matches no cluster in the evidence")
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--json", action="store_true", help="emit the raw statistics as JSON")
    parser.add_argument("--out", type=Path, help="write the markdown report to this path")
    parser.add_argument("--check", action="store_true", help="verify quoted numbers against the evidence")
    parser.add_argument("--jobs-dir", type=Path, default=JOBS_DIR)
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args()

    rep = stats(args.jobs_dir)

    if args.check:
        problems = check(args.root, rep)
        if problems:
            print("\n".join(problems), file=sys.stderr)
            print(f"\nFAILED: {len(problems)} drifted number(s) — re-run the script and update the prose", file=sys.stderr)
            return 1
        print(f"quoted numbers match the evidence ({rep['postings_with_body_text']} postings with body text)")
        return 0

    if args.json:
        print(json.dumps(rep, indent=2))
        return 0

    markdown = render_markdown(rep)
    if args.out:
        args.out.write_text(markdown, encoding="utf-8")
        print(f"wrote {args.out}")
    else:
        print(markdown, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
